name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Chequear el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Usa una versión compatible con tu proyecto
        cache: 'npm'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm ci

    # 4. Construir el proyecto
    - name: Build project
      run: npm run build

    # 5. Deploy a GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist  # Carpeta de salida generada por Vite
